### PR TITLE
Ignore error of writing responses to aborted requests

### LINKED ISSUE #442: Error "Cannot read property 'w' of null at iterateHttpRequests" on aborted connections
```typescript
// server.ts
import { serve } from "https://deno.land/std/http/server.ts";

async function main() {
  for await (let req of serve(":80")) {
    req.respond({});
  }
}

main();
```

```
$ deno run --allow-net server.ts
/Users/<redacted>/Library/Caches/deno/deps/https/raw.githubusercontent.com/denoland/deno_std/master/http/server.ts:225:36
            await writeResponse(req.w, {
                                    ^
Uncaught TypeError: Cannot read property 'w' of null
    at iterateHttpRequests (file:///Users/<redacted>/Library/Caches/deno/deps/https/raw.githubusercontent.com/denoland/deno_std/master/http/server.ts:254:31)
```

```
$ autocannon localhost
Running 10s test @ localhost
10 connections

┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬──────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max      │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼──────────┤
│ Latency │ 0 ms │ 0 ms │ 1 ms  │ 2 ms │ 0.07 ms │ 0.39 ms │ 11.05 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴─────────┴──────────┘
┌───────────┬────────┬────────┬─────────┬─────────┬──────────┬─────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%     │ 97.5%   │ Avg      │ Stdev   │ Min    │
├───────────┼────────┼────────┼─────────┼─────────┼──────────┼─────────┼────────┤
│ Req/Sec   │ 22879  │ 22879  │ 27695   │ 28287   │ 27145.46 │ 1494.03 │ 22871  │
├───────────┼────────┼────────┼─────────┼─────────┼──────────┼─────────┼────────┤
│ Bytes/Sec │ 869 kB │ 869 kB │ 1.05 MB │ 1.08 MB │ 1.03 MB  │ 56.8 kB │ 869 kB │
└───────────┴────────┴────────┴─────────┴─────────┴──────────┴─────────┴────────┘

Req/Bytes counts sampled once per second.

299k requests in 11.06s, 11.3 MB read
```

When I restarted the server and ran another load test, it crashed again. Might not be related to the high load, though.

### PR DESCRIPTION
**Pull request by kt3k**
This PR fixes the case described in #442. The test case reproduces the case given by @MarkTiedemann in the comment ( https://github.com/denoland/deno_std/issues/442#issuecomment-495557424 ).

This change simply ignore the error when the writing failed.

I believe the corresponding part of go's std library is [here](https://github.com/golang/go/blob/1962dc88eb89cd37d3f9f85e8e4b7ad4915db089/src/net/http/server.go#L1858).
```go
fmt.Fprintf(c.rwc, "HTTP/1.1 "+publicErr+errorHeaders+publicErr)
```
This doesn't handle the error returned by `fmt.Fprintf`. So this patch follows the above.

closes #442

### CODE REVIEW

**Comment by zekth** [comment]
This swallow only aborted connections? Or it may swallow also unexpected errors? Just wondering.

**Comment by kt3k** [comment]
@zekth
This swallows errors mainly when it throws during responding 400 responses to already errored requests. It shouldn't affect any successful requests.

**Comment by kt3k** [comment]
I skipped the test case on windows because it doesn't implement `process.kill(...)` and I couldn't find an alternative.

File: http/util.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// Sleeps the given milliseconds and resolves.
+export function sleep(ms: number): Promise<void> {
```
Comment (zekth) [inline http/util.ts]: Nice addition. But we may also add this to _std? i often use it personnaly.

Comment (kt3k) [reply http/util.ts]: I agree. This util is very useful. I moved the function to `util/async.ts`. (I also changed the name to `delay` because it sounds more general and node.js has [delay](https://github.com/sindresorhus/delay) module with almost the same purpose.)

File: http/server_test.ts [hunk 2]
```diff
@@ -456,4 +458,47 @@ test({
...
+      await conn.write(new TextEncoder().encode("GET / HTTP/1.0\n\n"));
+      conn.close();
+
+      // Waits for the server to handle the above (broken) request
+      await delay(100);
+
+      assert(serverIsRunning);
+    } finally {
+      // Stops the sever.
+      p.kill(2); // SIGINT
```
Comment (ry) [inline http/server_test.ts]: You can use `Deno.Signal.SIGINT` here

File: http/testdata/simple_server.ts [hunk 3]
```diff
@@ -0,0 +1,9 @@
+import { serve } from "../server.ts";
```
Comment (ry) [inline http/testdata/simple_server.ts]: Can you add a comment describing the purpose of this
```
// This is an example of a server that responds with an empty body
```
