### PR TITLE
Fix prettier check in empty files

### LINKED ISSUE #298: BUG: Prettier check fails on empty files
I have a simple script:
```bash
deno --allow-run --fmt --ignore lib/
```

Output is clean and no file is formatted. However when I add `--check` option it outputs: 
```
deno --allow-run --fmt --ignore lib/ --check
Some files are not formatted
```
I've peeked into `prettier/main.ts` and it seems this line: https://github.com/denoland/deno_std/blob/e80f14489084d748bb52c4311519f5d0c7696f47/prettier/main.ts#L122 should output which files are not formatted, but that's not the case. 

Any ideas @kt3k ?

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #298 

CC @kt3k

### CODE REVIEW

File: prettier/main.ts [hunk 1]
```diff
@@ -107,8 +107,8 @@ async function checkFile(
   const text = await readFileIfExists(filename);
 
   if (!text) {
-    // The file is deleted. Skip.
-    return;
+    // The file is deleted or empty. Skip.
```
Comment (kt3k) [inline prettier/main.ts]: We changed the way to enumerate files (`git ls-files` -> `fs.wak` in #241) and therefore this function should never be called with deleted files. So I think it's better to remove `deleted or` part from the comment.

**Comment by kt3k** [comment]
Other parts look good to me.
