### PR TITLE
fix(cli): ensure unknown() is not called for collect args

### LINKED ISSUE #6773: The `unknown` callback is called on `collect` arguments in `parseArgs`.
**Describe the bug**

The `unknown` callback is invoked for arguments that exist in `collect`.

**Steps to Reproduce**

```ts
import { parseArgs } from "jsr:@std/cli@1.0.21";

const result = parseArgs(["--foo=bar"], {
  collect: ["foo"],
  unknown: (arg) => {
    console.log(`Unknown argument: ${arg}`);
  },
});

console.log(result);
```

```console
$ deno run repro.ts
Unknown argument: --foo=bar
{ _: [], foo: [ "bar" ] }
```

**Expected behavior**

The `unknown` callback should not be called when parsing a known argument declared in `collect`.

**Environment**

- OS: Linux
- deno version: 2.4.1
- std version: @std/cli@1.0.21

### PR DESCRIPTION
**Pull request by WasixXD**
Fix #6773

### CODE REVIEW

**Comment by WasixXD** [comment]
I think the CI failing is unrelated

File: cli/parse_args_test.ts [hunk 1]
```diff
@@ -1690,6 +1691,38 @@ Deno.test("parseArgs() handles types of collect args with known and unknown args
...
+    unknown: (_arg) => {
+    },
+  };
+  const spyOnOpts = spy(opts, "unknown");
+  try {
+    parseArgs(["--foo=bar"], opts);
+    assertSpyCalls(spyOnOpts, 0);
+  } finally {
+    spyOnOpts.restore();
+  }
```
Comment (iuioiua) [inline cli/parse_args_test.ts]:
```suggestion
  let called = 0;
  parseArgs(["--foo=bar"], {
    collect: ["foo"],
    unknown: (_arg) => { called++; },
  });
  assertEquals(called, 0);
```

File: cli/parse_args_test.ts [hunk 2]
```diff
@@ -1690,6 +1691,38 @@ Deno.test("parseArgs() handles types of collect args with known and unknown args
...
+    },
+  };
+
+  const spyOnOpts = spy(opts, "unknown");
+  try {
+    parseArgs(["--foo=bar", "--qux=baz"], opts);
+    assertSpyCalls(spyOnOpts, 2);
+  } finally {
+    spyOnOpts.restore();
+  }
```
Comment (iuioiua) [inline cli/parse_args_test.ts]:
```suggestion
  let called = 0;
  parseArgs(["--foo=bar", "--qux=baz"], {
    collect: ["baz", "bar"],
    unknown: (_arg) => { called++; },
  });
  assertEquals(called, 2);
```

File: cli/parse_args_test.ts [hunk 3]
```diff
@@ -2,6 +2,7 @@
 import { assertEquals, assertThrows } from "@std/assert";
 import { type Args, parseArgs, type ParseOptions } from "./parse_args.ts";
 import { assertType, type IsExact } from "@std/testing/types";
+import { assertSpyCalls, spy } from "@std/testing/mock";
```
Comment (iuioiua) [inline cli/parse_args_test.ts]:
```suggestion
```
