### PR TITLE
fix(fs/walk): filter special files

### LINKED ISSUE #1789: walk() fails on socket
**Describe the bug**

Running `walk('/Users/clemens')` does not check for sockets.

> DEBUG RS - deno_runtime::ops::fs:1168 - op_read_dir_async /Users/clemens/.docker/run/docker.sock
> error: Uncaught (in promise) Error: Not a directory (os error 20), readdir '/Users/clemens/.docker/run/docker.sock' for path "/Users/clemens/.docker/run/docker.sock"

MacOS says
```
file /Users/clemens/.docker/run/docker.sock
/Users/clemens/.docker/run/docker.sock: socket
```

**Steps to Reproduce**

On MacOS run

```typescript
import { walk } from "https://deno.land/std@0.120.0/fs/walk.ts";

for await (const entry of walk('/Users/clemens')) {
    console.log(entry.path,entry.isFile);
}
```

The checks in https://github.com/denoland/deno/blob/d44011a69e0674acfa9c59bd7ad7f0523eb61d42/runtime/ops/fs.rs#L1178 seems logic. What is wrong?

**Expected behavior**

Happy scanner the whole tree

**Environment**

- MacOS 11.6.2
- deno 1.17.1 (release, x86_64-apple-darwin)
- v8 9.7.106.15
- typescript 4.5.2
- std@0.120.0

### PR DESCRIPTION
**Pull request by bnoordhuis**
Don't error on special files like UNIX domain sockets. Filter them out
instead.

Fixes #1789.

<hr>

I opted to filter them out because you can't really do anything except unlink them but maybe they should be included instead? Produces entries that look like this though:
```
{
  path: "/foo",
  name: "bar.sock",
  isFile: false,
  isDirectory: false,
  isSymlink: false,
}
```
Feedback appreciated.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
The linter is failing on something that's definitely not my work. 🤦

**Comment by lucacasonato** [comment]
I would vote for including them. If we don't include them, someone will want to add an option for including them in a few months. Let's just include them now.

**Comment by bartlomieju** [comment]
> The linter is failing on something that's definitely not my work. 🤦

@bnoordhuis merge `main` and it will be fixed.

File: fs/walk_test.ts [hunk 1]
```diff
@@ -283,6 +283,20 @@ testWalk(
   },
 );
 
+// https://github.com/denoland/deno_std/issues/1789
+testWalk(
+  async (d: string) => {
```
Comment (clemens-tolboom) [inline fs/walk_test.ts:288]: VSCode says 'remove async'

File: fs/walk_test.ts [hunk 2]
```diff
@@ -283,6 +283,20 @@ testWalk(
...
+    return Deno.listen({ path: d + "/a", transport: "unix" });
+  },
+  async function unixSocket(listener: any) {
```
Comment (clemens-tolboom) [inline fs/walk_test.ts:291]: Let's type this `listener: Deno.Listener`

**Review by clemens-tolboom — COMMENTED** [review]
This fix the socket.

I'll change my PR into a fix for `mkfifo`

**Comment by bnoordhuis** [comment]
> I would vote for including them.

Done.

**Review by kt3k — APPROVED** [review]
LGTM!
