### PR TITLE
fix(node/worker_threads): Don't wait for parent message in web worker

### LINKED ISSUE #2181: `node/module.ts` hangs in a web worker
Because of node `worker_thread` detection. Fix coming.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #2181. Uses a different method for detecting if the environment is in a node worker thread so that web workers don't count. That way it doesn't wait for a parent startup message that is never coming.

### CODE REVIEW

File: node/worker_threads.ts [hunk 1]
```diff
@@ -176,10 +177,12 @@ if (!isMainThread) {
     notImplemented("parentPort.removeAllListeners");
 
   // Receive startup message
+  console.trace();
```
Comment (bartlomieju) [inline node/worker_threads.ts:180]: Remove?

File: node/worker_threads.ts [hunk 2]
```diff
@@ -176,10 +177,12 @@ if (!isMainThread) {
...
   [{ threadId, workerData, environmentData }] = await once(
     parentPort,
     "message",
   );
+  console.trace(threadId, workerData, environmentData);
```
Comment (bartlomieju) [inline node/worker_threads.ts:185]: Remove?

File: node/worker_threads.ts [hunk 3]
```diff
@@ -54,7 +55,7 @@ class _Worker extends EventEmitter {
     const handle = this[kHandle] = new Worker(
       specifier,
       {
-        ...(options || {}),
+        name: PRIVATE_WORKER_THREAD_NAME,
```
Comment (bartlomieju) [inline node/worker_threads.ts:58]: This will cause all workers to have the same name; maybe we could add some kind of counter?

Comment (nayeemrmn) [reply node/worker_threads.ts:58]: Cross worker counter seems like a pain, I thought about `Date.now()` but that's unreliable as well...

The name doesn't serve another purpose and is deleted by the worker on startup, it's probably fine.

**Review by bartlomieju — APPROVED** [review]
LGTM
