### PR TITLE
fix(testing): `assertThrowsAsync` always reporting `Error` instead of actual error class

### LINKED ISSUE #967: assertThrowsAsync inconsistent with assertThrows, error message shows wrong actual error class
When you assert an error class but a different error was thrown, the message for assertThrows ends with ', but was "ExampleError".'. the message for assertThrowsAsync has a similar message except instead of "was" it says "got" and it always shows the actual as being "Error" incorrectly. I would expect all the tests to pass if assertThrowsAsync was working correctly.

I have deno 1.11.0 installed. Below is a minimum reproduction path. The assertThrows tests and the assertThrowsAsync test pass, but the 2 tests for what error assertThrowsAsync should throw fail.

```ts
import {
  AssertionError,
  assertThrows,
  assertThrowsAsync,
} from "https://deno.land/std@0.98.0/testing/asserts.ts";

class ExampleError extends Error {}
class OtherError extends Error {}

Deno.test("assertThrows", () => {
  assertThrows(
    () => {
      throw new ExampleError("failed");
    },
    ExampleError,
    "fail",
  );
});

Deno.test("assertThrows error", () => {
  assertThrows(
    () =>
      assertThrows(
        () => {
          throw new ExampleError("failed");
        },
        OtherError,
        "fail",
      ),
    AssertionError,
    'Expected error to be instance of "OtherError", but was "ExampleError".',
  );
});

Deno.test("assertThrowsAsync", async () => {
  await assertThrowsAsync(
    () => Promise.reject(new ExampleError("failed")),
    ExampleError,
    "fail",
  );
});

Deno.test("assertThrowsAsync promise rejected", async () => {
  await assertThrowsAsync(
    () =>
      assertThrowsAsync(
        () => Promise.reject(new ExampleError("failed")),
        OtherError,
        "fail",
      ),
    AssertionError,
    'Expected error to be instance of "OtherError", but was "ExampleError".',
  );
});

Deno.test("assertThrowsAsync error thrown in async function", async () => {
  await assertThrowsAsync(
    () =>
      assertThrowsAsync(
        async () => {
          await Promise.resolve();
          throw new ExampleError("failed");
        },
        OtherError,
        "fail",
      ),
    AssertionError,
    'Expected error to be instance of "OtherError", but was "ExampleError".',
  );
});
```

```
$ deno test example_test.ts
running 5 tests from file:///home/kyle/Projects/deno/mock/example_test.ts
test assertThrows ... ok (2ms)
test assertThrows error ... ok (2ms)
test assertThrowsAsync ... ok (1ms)
test assertThrowsAsync promise rejected ... FAILED (1ms)
test assertThrowsAsync error thrown in async function ... FAILED (2ms)

failures:

assertThrowsAsync promise rejected
AssertionError: Expected error message to include "Expected error to be instance of "OtherError", but was "ExampleError".", but got "Expected error to be instance of "OtherError", but got "Error".".
    at assertThrowsAsync (https://deno.land/std@0.98.0/testing/asserts.ts:632:13)
    at async file:///home/kyle/Projects/deno/mock/example_test.ts:44:3
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:21:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:58:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)
    at async file:///home/kyle/Projects/deno/mock/$deno$test.js:1:1

assertThrowsAsync error thrown in async function
AssertionError: Expected error message to include "Expected error to be instance of "OtherError", but was "ExampleError".", but got "Expected error to be instance of "OtherError", but got "Error".".
    at assertThrowsAsync (https://deno.land/std@0.98.0/testing/asserts.ts:632:13)
    at async file:///home/kyle/Projects/deno/mock/example_test.ts:57:3
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:21:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:58:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)
    at async file:///home/kyle/Projects/deno/mock/$deno$test.js:1:1

failures:

        assertThrowsAsync promise rejected
        assertThrowsAsync error thrown in async function

test result: FAILED. 3 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out (45ms)
```

### PR DESCRIPTION
**Pull request by lowlighter**
Closes #967

As `assertThrowsAsync` has an implementation drift from `assertThrows` which result in hiding the actual typing of errors in result messages when using custom errors:

```ts
class CustomError extends Error {}
Deno.test("test", async () => void await assertThrowsAsync(() => Promise.reject(new CustomError()), TypeError))
```

Before (making test harder to debug):
```
AssertionError: Expected error to be instance of "TypeError", but got "Error".
```

After:
```
AssertionError: Expected error to be instance of "TypeError", but got "CustomError ".
```

___
References:

AssertThrows:
https://github.com/denoland/deno_std/blob/e4c6419c466335eb697df38a387a2def06e6f3c5/testing/asserts.ts#L598

AssertThrowsAsync:
https://github.com/denoland/deno_std/blob/e4c6419c466335eb697df38a387a2def06e6f3c5/testing/asserts.ts#L644

### CODE REVIEW

**Comment by bartlomieju** [comment]
@lowlighter the fix looks good, could you exercise this change in `testing/asserts_test.ts` and check that the returned message is as expected?

**Review by bartlomieju — APPROVED** [review]

File: testing/asserts_test.ts [hunk 1]
```diff
@@ -1039,3 +1039,18 @@ Deno.test("Assert Throws Async Parent Error", () => {
...
+  class AnotherCustomError extends Error {}
+  await assertThrowsAsync(
+    () =>
+      assertThrowsAsync(
+        () => Promise.reject(new AnotherCustomError("failed")),
+        CustomError,
+        "fail",
+      ),
+    AssertionError,
+    'Expected error to be instance of "CustomError", but was "AnotherCustomError".',
```
Comment (kt3k) [inline testing/asserts_test.ts:1054]: :+1:

**Review by kt3k — APPROVED** [review]
@lowlighter Thank you for your contribution! LGTM

File: testing/asserts_test.ts (hunk 1 above)
Comment (jsejcksn) [reply testing/asserts_test.ts:1054]: @kt3k (I know this is already merged, but...)

Is there a convention for grammar in error messages?

For example, things like:
- terminating punctuation vs no terminating punctuation:
  - `"File not found."`
  - `"File not found"`
- conventional verbs (i.e. _got_/_saw_/_was_/etc.)
  - `"Expected x but saw y"`
  - `"Expected x but got y"`
- etc.

Comment (kt3k) [reply testing/asserts_test.ts:1054]: @jsejcksn I don't think we have an explicit rule about it. But I think we should have one. Suggestions are welcome
