### PR TITLE
fix(node/tls): fix TLSSocket constructor

### LINKED ISSUE #2701: node TLSSocket throws TypeError if opts undefined
**Describe the bug**

TypeError thrown if opts is undefined...

https://deno.land/std@0.157.0/node/_tls_wrap.ts?source=#L70

```typescript
  constructor(socket: any, opts: any) {
    const tlsOptions = { ...opts };

    let hostname = tlsOptions?.secureContext?.servername;
    hostname = opts.host;
    tlsOptions.hostname = hostname;
```

The line `hostname = opts.host;` throws an error if opts was undefined.

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'host')
    hostname = opts.host;
                    ^
    at new TLSSocket (https://deno.land/std@0.157.0/node/_tls_wrap.ts:70:21)
```

but also, it doesn't make sense, as hostname may already be set and then this line completely overrides the line above (or errors).

**Steps to Reproduce**

I was attempting to run `web-ext` cli directly from npm to see if it worked from Deno...

```
deno run --unstable --allow-env --allow-read npm:web-ext --version
```

**Expected behavior**

For web-ext to run and output it's version number.

**Environment**

- OS: MacOS 12.4
- deno version: 1.25.4 (release, x86_64-apple-darwin)
- std version: 0.157.0

### PR DESCRIPTION
**Pull request by kt3k**
closes #2701

### CODE REVIEW

File: node/_tls_wrap.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ export class TLSSocket extends net.Socket {
   [kConnectOptions]: any;
   ssl: any;
   _start: any;
-  constructor(socket: any, opts: any) {
+  constructor(socket: any, opts: any = {}) {
```
Comment (cjihrig) [inline node/_tls_wrap.ts:66]: Consider using `kEmptyObject` instead of creating a new object here.

**Review by cjihrig — APPROVED** [review]
