### PR TITLE
fix(expect): align toEqual to jest

### LINKED ISSUE #3947: Expect toEqual: undefined properties are required in the expected value
**Describe the bug**

When using `expect().toEqual`, undefined properties in the test value cause a failure when those properties don't exist in the expect value.

**Steps to Reproduce**

```typescript
import { expect as denoExpect } from "https://deno.land/std/expect/mod.ts";
import { expect as npmExpect } from "npm:expect";

// Passes
Deno.test("npm expect().toEqual ignores undefined values", () => {
  npmExpect({
    prop1: "string",
    prop2: undefined,
  }).toEqual({
    prop1: "string",
  });
});

// Fails
Deno.test("deno expect().toEqual ignores undefined values", () => {
  denoExpect({
    prop1: "string",
    prop2: undefined,
  }).toEqual({
    prop1: "string",
  });
});
```

**Expected behavior**

I expect `deno expect` to behave the same as `npm expect` and the test above should have passed. If there are undefined properties in the test value, those properties shouldn't need to exist in the expect value.

**Environment**

- OS: MacOS 13.6.3 ARM
- deno version: 1.38.5
- std version: latest main and stable (0.208.0)

### PR DESCRIPTION
**Pull request by kt3k**
This PR updates `expect().toEqual()` behavior. Now the difference of `undefined`-valued keys are ignored in objects.

closes #3947

### CODE REVIEW

File: expect/_matchers.ts
Comment (iuioiua) [inline expect/_matchers.ts:1]: What about using https://deno.land/std/collections/mod.ts?s=filterValues ?

Comment (kt3k) [reply expect/_matchers.ts:1]: `filterValues` only filters one level (immediate child values of the root object), but this needs to filter recursively.

File: expect/_matchers.ts [hunk 1]
```diff
@@ -26,14 +26,37 @@ export function toBe(context: MatcherContext, expect: unknown): MatchResult {
...
+// deno-lint-ignore no-explicit-any
+function filterUndefined(obj: any): any {
+  if (typeof obj !== "object") return obj;
+  if (obj instanceof Date) return obj;
+  if (obj instanceof RegExp) return obj;
+  if (ArrayBuffer.isView(obj)) return obj;
+  if (obj === null) return obj;
+  if ("size" in obj) return obj;
+  if (Symbol.iterator in obj) return obj;
+  if (Array.isArray(obj)) return obj.map(filterUndefined);
```
Comment (iuioiua) [inline expect/_matchers.ts:38]: Nit: Perhaps this logic could be factored out into its own `isPlainObject()` just so its purpose is made clear.

**Review by iuioiua — APPROVED** [review]
