### PR TITLE
fix(datetime): `.quarter` calculation for `difference()`

### LINKED ISSUE #3080: datetime/mod.ts: difference incorrect for 'quarters'
**Describe the bug**

difference results in incorrect value for 'quarters'

**Steps to Reproduce**

```javascript
import { difference } from "https://deno.land/std@0.170.0/datetime/mod.ts";

const date0 = new Date("2018-05-14");
const date1 = new Date("2020-06-13");

console.log(difference(date0, date1));
```
The output is:
```js
{
  milliseconds: 65750400000,
  seconds: 65750400,
  minutes: 1095840,
  hours: 18264,
  days: 761,
  weeks: 108,
  months: 24,
  quarters: 6,
  years: 2
}
```

**Expected behavior**

If the value for months is `24` the value for quarters should be `8` instead of `6`.... right?

**Environment**

- OS: macOS Ventura 13.1 (22C65)
- deno version: 1.29.1 (release, aarch64-apple-darwin)
- std version: 0.170.0

### PR DESCRIPTION
**Pull request by iuioiua**
This change fixes #3080 and simplifies some logic behind the function.

### CODE REVIEW

File: datetime/difference.ts [hunk 1]
```diff
@@ -113,20 +101,18 @@ export function difference(
...
-        differences.months = calculateMonthsDifference(bigger, smaller);
+        differences.months = calculateMonthsDifference(from, to);
         break;
       case "quarters":
         differences.quarters = Math.floor(
-          (typeof differences.months !== "undefined" &&
-            differences.months / 4) ||
-            calculateMonthsDifference(bigger, smaller) / 4,
+          (differences.months !== undefined && differences.months / 3) ||
+            calculateMonthsDifference(from, to) / 3,
```
Comment (kt3k) [inline datetime/difference.ts:109]: 👍

**Review by kt3k — APPROVED** [review]
LGTM. Thanks! @iuioiua
