### PR TITLE
fix(fs): fix NotFound error when moving src to itself with overwrite: true

### LINKED ISSUE #3288: `std/fs/move` doesn't check if `src` and `dest` differ
**Describe the bug**
The actual issue is that `move` with `overwrite` option set to `true` removes `dest` as the first action. The result is that `src` ends up deleted and deno complains that it can't find the path to rename.

**Steps to Reproduce**
1. Execute in a directory containing directory `a`:
```ts
move("a", "a", { overwrite: true });
```
2. Directory `a` is gone.

**Expected behavior**

Nothing happens.

**Environment**

- OS: Windows 10
- deno version: 1.31.1
- std version: 0.181.0

### PR DESCRIPTION
**Pull request by tetraphobia**
Resolves #3288

Moving a file to itself with the overwrite option set to true results in the original file being deleted and a NotFound error being thrown. This implements a simple guard against these scenarios.

### CODE REVIEW

File: fs/move.ts [hunk 1]
```diff
@@ -30,6 +31,14 @@ export async function move(
     );
   }
 
+  const srcAbsolute = src instanceof URL ? src.pathname : resolve(src)
+  const destAbsolute = dest instanceof URL ? dest.pathname : resolve(dest)
+
+  if (srcAbsolute === destAbsolute) {
+    await Deno.rename(src, dest)
```
Comment (kt3k) [inline fs/move.ts:38]: Is this rename meaningful?

File: fs/move.ts [hunk 2]
```diff
@@ -30,6 +31,14 @@ export async function move(
     );
   }
 
+  const srcAbsolute = src instanceof URL ? src.pathname : resolve(src)
+  const destAbsolute = dest instanceof URL ? dest.pathname : resolve(dest)
+
+  if (srcAbsolute === destAbsolute) {
```
Comment (kt3k) [inline fs/move.ts:37]: Can this check made into a common util in `fs/_util.ts`? (like `isSubdir`)

File: fs/move_test.ts [hunk 3]
```diff
@@ -374,3 +374,93 @@ Deno.test("moveSyncIntoSubDir", function () {
...
+  // ensure test data exists
+  await Deno.mkdir(srcDir, { recursive: true });
+  assert(await Deno.lstat(srcDir));
+  await Deno.writeFile(srcFile, srcContent);
+
+  // move file to itself with overwrite
+  await move(srcFile, srcFile, { overwrite: true });
+  await move(srcFile, srcUrl, { overwrite: true });
+  await move(srcUrl, srcFile, { overwrite: true });
+  await move(srcUrl, srcUrl, { overwrite: true });
```
Comment (kt3k) [inline fs/move_test.ts:415]: I think this should move directory, according to the test title
```suggestion
  await move(srcDir, srcDir, { overwrite: true });
```

File: fs/move_test.ts [hunk 4]
```diff
@@ -374,3 +374,93 @@ Deno.test("moveSyncIntoSubDir", function () {
...
+
+  // test file should be untouched
+  assertEquals(new TextDecoder().decode(await Deno.readFile(srcFile)), "src");
```
Comment (kt3k) [inline fs/move_test.ts:395]: You can use `Deno.readTextFile()` and skip using `TextDecoder`

File: fs/move.ts (hunk 1 above)
Comment (tetraphobia) [reply fs/move.ts:38]: I don't feel like it is, since the result will be the same. I put the rename there just in case it would be overriding some behavior during rename.

File: fs/move.ts (hunk 2 above)
Comment (tetraphobia) [reply fs/move.ts:37]: Will do.

File: fs/_util.ts [hunk 5]
```diff
@@ -1,6 +1,22 @@
...
+
+/**
+ * Test whether `src` and `dest` resolve to the same location
+ * @param src src file path
+ * @param dest dest file path
+ */
+export function isSamePath(
+  src: string | URL,
+  dest: string | URL,
+  sep: string = path.sep,
```
Comment (kt3k) [inline fs/_util.ts:13]: The 3rd parameter looks only used in testing. Do we really need this?

Comment (kt3k) [reply fs/_util.ts:13]: (We usually don't need to specify platform specific params explicitly because they are abstracted by path module)

Comment (tetraphobia) [reply fs/_util.ts:13]: > The 3rd parameter looks only used in testing. Do we really need this?

Idealy not. I had some trouble producing consistent results in the tests involving mixed URL and string params using win32 paths. It's probably just a testing issue, and I will look for a better solution in the meantime.

Comment (tetraphobia) [reply fs/_util.ts]: Today I discovered the `ignore` option and fixed the issue :)

**Review by kt3k — APPROVED** [review]
LGTM. Nice work!
