### PR TITLE
fix(fs): reduce perm requirement of `ensureDir()`

### LINKED ISSUE #3233: `ensureDir` and `ensureDirSync` are racy
They do `lstat` then `mkdir` rather than doing only `mkdir` and throwing an error.

If you call `ensureDir` quickly enough in parallel, one of the two `ensureDir`'s will throw "AlreadyExists".

"exists" checks using something like `lstat` are wrong 99% of times, and this is no exception :)

### LINKED ISSUE #3339: Fixing racy ensureDirSync broke ensureFileSync for tight permissions
I just updated our used version of deno std and the changes made to `ensureDir` and `ensureDirSync` in https://github.com/denoland/deno_std/pull/3242 break our unit tests. While I am in favor of fixing the race condition, I feel like one side effect has not been considered that could be easily solved (so I think, see proposal below).

The changes introduced in https://github.com/denoland/deno_std/pull/3242 make it so that `ensureFile` and `ensureFileSync` no longer work with write permissions limited to specific files, they would require write permissions to their parent directories now due to their internal usage of `ensureDir` and `ensureDirSync`

This can be easily tested with this example code (first two tests, rest is my proposed fix):
```ts
import { ensureFileSync as ensureFileSyncWithOldEnsureDirSync } from "https://deno.land/std@0.178.0/fs/mod.ts";
import {
  ensureDirSync,
  ensureFileSync as ensureFileSyncWithNewEnsureDirSync,
} from "https://deno.land/std@0.179.0/fs/mod.ts";
import {
  getFileInfoType,
  toPathString,
} from "https://deno.land/std@0.179.0/fs/_util.ts";
import * as path from "https://deno.land/std@0.179.0/path/mod.ts";

const testDirectory = "./tests";
const testFilepath = testDirectory + "/allowed-file";

ensureDirSync(testDirectory);

Deno.test(
  {
    name: "Works with old ensureDirSync",
    permissions: {
      read: [testDirectory],
      write: [testFilepath],
    },
  },
  () => {
    try {
      Deno.removeSync(testFilepath);
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) throw err;
    }
    ensureFileSyncWithOldEnsureDirSync(testFilepath);
  },
);

Deno.test(
  {
    name: "Does not work with new ensureDirSync",
    permissions: {
      read: [testDirectory],
      write: [testFilepath],
    },
  },
  () => {
    try {
      Deno.removeSync(testFilepath);
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) throw err;
    }
    ensureFileSyncWithNewEnsureDirSync(testFilepath);
  },
);

Deno.test(
  {
    name: "Would work with proposed ensureDirSync (but is it racy?)",
    permissions: {
      read: [testDirectory],
      write: [testFilepath],
    },
  },
  () => {
    try {
      Deno.removeSync(testFilepath);
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) throw err;
    }
    ensureFileSyncWithProposedEnsureDirSync(testFilepath);
  },
);

Deno.test(
  {
    name: "Proposed ensureDirSync also still works for directories",
    permissions: {
      read: [testDirectory],
      write: [testDirectory],
    },
  },
  () => {
    try {
      Deno.removeSync(testDirectory, { recursive: true });
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) throw err;
    }
    ProposedEnsureDirSync(testDirectory);
  },
);

Deno.test(
  {
    name:
      "Proposed ensureDirSync also still works for directories - throws on missing permission",
    permissions: {
      read: [testDirectory],
      write: [testDirectory],
    },
  },
  () => {
    try {
      Deno.removeSync(testDirectory, { recursive: true });
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) throw err;
    }
    Deno.permissions.revokeSync({ name: "write", path: testDirectory });
    ProposedEnsureDirSync(testDirectory);
  },
);

function ProposedEnsureDirSync(dir: string | URL) {
  try {
    Deno.mkdirSync(dir, { recursive: true });
  } catch (mkdirErr) {
    if (
      !(mkdirErr instanceof Deno.errors.AlreadyExists ||
        mkdirErr instanceof Deno.errors.PermissionDenied)
    ) {
      throw mkdirErr;
    }

    try {
      const fileInfo = Deno.lstatSync(dir);
      if (!fileInfo.isDirectory) {
        throw new Error(
          `Ensure path exists, expected 'dir', got '${
            getFileInfoType(fileInfo)
          }'`,
        );
      }
    } catch (lstatErr) {
      if (
        mkdirErr instanceof Deno.errors.PermissionDenied &&
        lstatErr instanceof Deno.errors.NotFound
      ) {
        throw mkdirErr;
      } else {
        throw lstatErr;
      }
    }
  }
}

// ensureFileSync from 0.185.0, just using the ensureDirSync proposed here
function ensureFileSyncWithProposedEnsureDirSync(filePath: string | URL) {
  try {
    // if file exists
    const stat = Deno.lstatSync(filePath);
    if (!stat.isFile) {
      throw new Error(
        `Ensure path exists, expected 'file', got '${getFileInfoType(stat)}'`,
      );
    }
  } catch (err) {
    // if file not exists
    if (err instanceof Deno.errors.NotFound) {
      // ensure dir exists
      ProposedEnsureDirSync(path.dirname(toPathString(filePath)));
      // create file
      Deno.writeFileSync(filePath, new Uint8Array());
      return;
    }
    throw err;
  }
}
```

Output
```
$ deno test --allow-read --allow-write minimal.test.ts
running 5 tests from ./minimal.test.ts
Works with old ensureDirSync ... ok (13ms)
Does not work with new ensureDirSync ... FAILED (5ms)
Would work with proposed ensureDirSync (but is it racy?) ... ok (5ms)
Proposed ensureDirSync also still works for directories ... ok (5ms)
Proposed ensureDirSync also still works for directories - throws on missing permission ... FAILED (5ms)

 ERRORS 

Does not work with new ensureDirSync => ./minimal.test.ts:35:6
error: PermissionDenied: Requires write access to "./tests", run again with the --allow-write flag
    Deno.mkdirSync(dir, { recursive: true });
         ^
    at Object.mkdirSync (ext:deno_fs/30_fs.js:118:7)
    at ensureDirSync (https://deno.land/std@0.179.0/fs/ensure_dir.ts:49:10)
    at ensureFileSync (https://deno.land/std@0.179.0/fs/ensure_file.ts:72:7)
    at file:///home/egf0s02d/projects/minion/minimal.test.ts:49:5

Proposed ensureDirSync also still works for directories - throws on missing permission => ./minimal.test.ts:89:6
error: PermissionDenied: Requires write access to "./tests", run again with the --allow-write flag
    Deno.mkdirSync(dir, { recursive: true });
         ^
    at Object.mkdirSync (ext:deno_fs/30_fs.js:118:7)
    at ProposedEnsureDirSync (file:///home/egf0s02d/projects/minion/minimal.test.ts:111:10)
    at file:///home/egf0s02d/projects/minion/minimal.test.ts:105:5

 FAILURES 

Does not work with new ensureDirSync => ./minimal.test.ts:35:6
Proposed ensureDirSync also still works for directories - throws on missing permission => ./minimal.test.ts:89:6

FAILED | 3 passed | 2 failed (82ms)

error: Test failed
```

As you can see I already included a proposed fix, that is changing the implementation from this
https://github.com/denoland/deno_std/blob/aa57bf337bbf5e061752b92164b003a60e728951/fs/ensure_dir.ts#L47-L64

to this
```ts
export function ensureDirSync(dir: string | URL) {
  try {
    Deno.mkdirSync(dir, { recursive: true });
  } catch (mkdirErr) {
    if (
      !(mkdirErr instanceof Deno.errors.AlreadyExists ||
        mkdirErr instanceof Deno.errors.PermissionDenied)
    ) {
      throw mkdirErr;
    }

    try {
      const fileInfo = Deno.lstatSync(dir);
      if (!fileInfo.isDirectory) {
        throw new Error(
          `Ensure path exists, expected 'dir', got '${
            getFileInfoType(fileInfo)
          }'`,
        );
      }
    } catch (lstatErr) {
      if (
        mkdirErr instanceof Deno.errors.PermissionDenied &&
        lstatErr instanceof Deno.errors.NotFound
      ) {
        throw mkdirErr;
      } else {
        throw lstatErr;
      }
    }
  }
}
```

so if the directory creation fails due to missing write privileges, but it already exists, then we are fine, if it does not exist we just rethrow the original error.

This being a friday evening fix, there may be circumstances I have not considered yet, so I'll just leave that here to get some input.

- OS: Rocky Linux 8 + 9
- deno version: 1.32.5
- std version: 0.179.0+

### PR DESCRIPTION
**Pull request by kt3k**
Another attempt to solve #3339. (ref. #4008)

This PR updates `ensureDir` behavior. It now first checks the lstat of the path, then tries `mkdir`, then catches `AlreadyExists` error and checks the lstat of the path again. This reduces the permission requirement to the given dir to only `read` permission when the path already exists (currently `write` is always required), and also doesn't fail with concurrent calls (doesn't re-introduce #3233).

closes #3339 
closes #3233

### CODE REVIEW

File: fs/ensure_dir.ts [hunk 1]
```diff
@@ -14,6 +14,24 @@ import { getFileInfoType } from "./_get_file_info_type.ts";
  * ```
  */
 export async function ensureDir(dir: string | URL) {
+  try {
+    const fileInfo = await Deno.lstat(dir);
```
Comment (joehillen) [inline fs/ensure_dir.ts:18]: Using `lstat` instead of `stat` means that it will consider links to directories as links and not directories. I dont think it's good behavior as I often use links to trick programs into changing where files are stored. Any use case involving `ensureDir` will likely consider a link to a directory as acceptable.

Comment (joehillen) [reply fs/ensure_dir.ts:18]: I've opened a PR to your branch here: https://github.com/kt3k/deno_std/pull/1

Comment (kt3k) [reply fs/ensure_dir.ts:18]: That looks like a breaking change. I think we should work on that as an independent issue.

**Review by egfx-notifications — APPROVED** [review]
LGTM, thank you!

**Review by bartlomieju — APPROVED** [review]
