### PR TITLE
fix(node): ignore shebang

### LINKED ISSUE #730: node/module: shebang should be ignored
In node.js, shebang line is ignored when the script is loaded as commonjs module.

cli.js
```js
#!/usr/bin/env node
console.log(42);
```
test-node.js
```js
require("./cli");
```
The above runs without any error, but with `node/module.ts` the above throws compile error.

test-deno.js:
```js
import { createRequire } from "https://deno.land/std@0.87.0/node/module.ts";
try {
  createRequire(import.meta.url)("./cli");
} catch (e) {
  console.log(e);
}
```

It throws a compile error.
```shellsession
$ deno run --unstable -A test-deno.js
{
  isCompileError: true,
  isNativeError: true,
  thrown: SyntaxError: Invalid or unexpected token
    at wrapSafe (module.ts:1060:39)
    at Module._compile (module.ts:153:29)
    at Object.Module._extensions..js (module.ts:1077:10)
    at Module.load (module.ts:141:34)
    at Function._load (module.ts:407:14)
    at Module.require (module.ts:127:21)
    at require (module.ts:1126:16)
    at file:///Users/kt3k/denoland/deno_std/test-deno.js:3:33
}
```

Most cli node modules have shebang line, so this prevents using cli tools using our node.js compatibility layer.

### PR DESCRIPTION
**Pull request by Liamolucko**
Resolves #730

### CODE REVIEW

**Review by satyarohith — COMMENTED** [review]
LGTM!

(Thanks for raising an issue about `fmt` removing comments.)

File: node/_module/shebang.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+#!/usr/bin/env node
```
Comment (caspervonb) [inline node/_module/shebang.js:1]: Stick this in testdata? 🤔

**Review by kt3k — APPROVED** [review]
LGTM. Thank you, @Liamolucko!
