### PR TITLE
BREAKING(fmt): rename stripColor to stripAnsiCode

### LINKED ISSUE #3580: rename stripColor to stripAnsi
In my opinion stripColor gives the wrong impression, there are many ansi sequences that are not colors

### PR DESCRIPTION
**Pull request by lino-levan**
Closes #3580

### CODE REVIEW

File: fmt/colors.ts [hunk 1]
```diff
@@ -562,9 +562,19 @@ const ANSI_PATTERN = new RegExp(
...
 
 /**
+ * @deprecated (will be removed in 1.0.0) Use `stripAnsiCode` instead.
+ *
  * Remove ANSI escape codes from the string.
  * @param string to remove ANSI escape codes from
  */
 export function stripColor(string: string): string {
   return string.replace(ANSI_PATTERN, "");
 }
```
Comment (iuioiua) [inline fmt/colors.ts:572]:
```suggestion
export const stripColor = stripAnsiCode;
```
Nit

**Review by iuioiua — CHANGES_REQUESTED** [review]

**Review by iuioiua — APPROVED** [review]

**Comment by lino-levan** [comment]
Another flaky test failure it appears

**Review by kt3k — APPROVED** [review]
LGTM. Thanks
