### PR TITLE
fix(msgpack): encode huge objects #3696

### LINKED ISSUE #3696: msgpack.encode fails with `RangeError: Maximum call stack size exceeded` on big objects
**Describe the bug**
My app may receive huge jsons (with thousands of items and very complex structure) and shall re-encode the json into msgpack. 
JSON.parse works perfectly fine but msgpack.encode fails with `Uncaught RangeError: Maximum call stack size exceeded`.

**Steps to Reproduce**
Here is a simple code to reproduce it:

```ts
const bigObject = {};

for (let i = 0; i < 50000; i++) {
  Object.defineProperty(bigObject, `prop_${i}`, {
    value: i,
    enumerable: true
  });
}

import * as msgpack from "https://deno.land/std@0.204.0/msgpack/mod.ts";
const m = msgpack.encode(bigObject);
```

**Expected behavior**
Should not fail and return the encoded Uint8Array.

**Environment**

- OS: [WSL-Ubuntu 22.04]
- deno version: `{ deno: "1.37.0", v8: "11.8.172.3", typescript: "5.2.2" }`
- std version: 0.204.0

### PR DESCRIPTION
**Pull request by pavel-lechenko**
This PR resolves #3696

Also required to adjust `concat` function so that it also supports `Uint8Array[][]`.

### CODE REVIEW

File: bytes/concat.ts [hunk 1]
```diff
@@ -8,18 +8,32 @@
  * const a = new Uint8Array([0, 1, 2]);
  * const b = new Uint8Array([3, 4, 5]);
  * console.log(concat(a, b)); // [0, 1, 2, 3, 4, 5]
+ * ```
  */
-export function concat(...buf: Uint8Array[]): Uint8Array {
+export function concat(...buf: Uint8Array[] | Uint8Array[][]): Uint8Array {
```
Comment (lino-levan) [inline bytes/concat.ts:13]: This isn't how I would accomplish this overload. I'd probably have two possible signatures: One `buffer: Uint8Array[]` and one `...buf: Uint8Array[]`.

**Review by lino-levan — CHANGES_REQUESTED** [review]

File: bytes/concat.ts (hunk 1 above)
Comment (aapoalas) [reply bytes/concat.ts:13]: Agreed: Check if length is one and then check type:
* Array? Presume array of Uint8Arrays and concat them directly.
* Uint8Array? Return directly as concating a single item requires no copy work.

Comment (pavel-lechenko) [reply bytes/concat.ts:13]: The approach of having such overloads causes signature incompatibility. Do you have an idea how to avoid the conflict?

Also Microsoft recommends using the union as a good practice in case of multiple types: https://www.typescriptlang.org/docs/handbook/2/functions.html#writing-good-overloads

Comment (pavel-lechenko) [reply bytes/concat.ts:13]: Another approach is to copy-paste `concat` into msgpack/encode.ts so it accepts a single argument of type `Uint8Array[]`. 
What do you think?

Comment (pavel-lechenko) [reply bytes/concat.ts:13]: Like this:
```ts
export function encode(object: ValueType) {
  const byteParts: Uint8Array[] = [];
  encodeSlice(object, byteParts);
  
  // Concat byteParts into output 
  let length = 0;
  for (const b of byteParts) {
    length += b.length;
  }
  const output = new Uint8Array(length);
  let index = 0;
  for (const b of byteParts) {
    output.set(b, index);
    index += b.length;
  }
  return output;  
}
```

Comment (aapoalas) [reply bytes/concat.ts:13]: A possible union typing is `Uint8Array[] | [Uint8Array[]]`.

Comment (pavel-lechenko) [reply bytes/concat.ts]: @aapoalas implemented per your suggestion together with tests. 
Used `(Uint8Array | Uint8Array[])[]` for better readability and LSP support.

File: bytes/concat.ts
Comment (iuioiua) [inline bytes/concat.ts:1]: What about factoring the new logic into a `concatDeep()`? It might be a bit easier to follow.

Comment (iuioiua) [reply bytes/concat.ts:1]: On top of this, can you please run `deno fmt`?

File: bytes/concat.ts [hunk 2]
```diff
@@ -8,18 +8,41 @@
  * const a = new Uint8Array([0, 1, 2]);
  * const b = new Uint8Array([3, 4, 5]);
  * console.log(concat(a, b)); // [0, 1, 2, 3, 4, 5]
+ * ```
  */
-export function concat(...buf: Uint8Array[]): Uint8Array {
+export function concat(...buf: (Uint8Array | Uint8Array[])[]): Uint8Array {
```
Comment (lino-levan) [inline bytes/concat.ts:13]: Could you overload these operators like so?
```suggestion
export function concat(buf: Uint8Array[]): Uint8Array;
export function concat(...buf: Uint8Array[]): Uint8Array;
export function concat(...buf: (Uint8Array | Uint8Array[])[]): Uint8Array {
```

**Review by lino-levan — CHANGES_REQUESTED** [review]

**Comment by iuioiua** [comment]
@pavel-lechenko, PTAL at https://github.com/denoland/deno_std/issues/3696#issuecomment-1776424324

File: bytes/concat.ts (hunk 2 above)
Comment (pavel-lechenko) [reply bytes/concat.ts:13]: Sure, but in this case it won't work for multiple arrays of Uint8Array. So it will support only one array.

I will make a change as suggested.

**Comment by iuioiua** [comment]
I've played around with this, and it seems that all that's needed is to remove the spread operator from `concat()` and add the new tests for `concat()` and `encode()`. IIUC, `concat()` doesn't need to accept anything more than `Uint8Array[]`, as all tests pass fine.

**Review by lino-levan — APPROVED** [review]
I think this LGTM. Obviously not the only way to solve the problem.

**Review by aapoalas — APPROVED** [review]
LGTM as well.

**Comment by iuioiua** [comment]
@pavel-lechenko, please see my previous comment.

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
@iuioiua Do you suggest removing spread operator? I think we should always avoid breaking changes if possible.

**Comment by iuioiua** [comment]
Yes, I don't think `concat()` needs to cater for arrays deeper than 1. Having it accept an array makes much more sense to me. I think it's better to make the breaking change than complicating it.

**Comment by kt3k** [comment]
@pavel-lechenko Thanks for your contribution!

We'll continue working on @iuioiua's point in later PRs.
